name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: logix-tool/github-actions/cargo-deny@main
      with:
          token: ${{ secrets.READ_PUBLIC_TOKEN }}

    - uses: logix-tool/github-actions/cargo-semver-checks@main
      with:
          token: ${{ secrets.READ_PUBLIC_TOKEN }}

    - name: Run linters
      run: |
          cargo fmt --check --verbose
          cargo clippy --verbose

    - name: Run build
      run: |
          echo "Debug build"
          cargo build
          echo "Build tests"
          cargo build --tests
          echo "Release build"
          cargo build --release

    - name: Run checks
      run: |
        echo "Running cargo deny check"
        cargo deny check

        echo "Running cargo semver-checks"
        cargo semver-checks

        echo "Running cargo outdated"
        cargo outdated --exit-code 1

        # TODO(2023.10): requires nightly
        #echo "Running cargo udeps"
        #rustup run nightly cargo udeps

        # TODO(2023.10): no pre-built binary?
        #echo "Running cargo audit"
        #rustup cargo audit

        # TODO(2023.10): no pre-built binary?
        #echo "Running cargo pants"
        #rustup cargo pants
